[build]
builder = "nixpacks"
buildCommand = "pnpm install"

[deploy]
startCommand = "pnpm start"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"

[[services]]
name = "x402-api"